name: game_server
description: Backend para el juego de cartas multijugador.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.0
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
