name: clonacion
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  uuid: ^4.3.3
  intl: ^0.19.0
  animate_do: ^3.3.2
  shared_preferences: ^2.2.2
  postgres: ^2.6.0
  crypto: ^3.0.7
  web_socket_channel: ^2.4.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/androide/
    - assets/avatars/ainara/
    - assets/avatars/cientifico/
    - assets/avatars/timida/
  fonts:
    - family: SpaceMono
      fonts:
        - asset: fonts/SpaceMono-Regular.ttf
        - asset: fonts/SpaceMono-Bold.ttf
          weight: 700
    - family: LexendMega
      fonts:
        - asset: fonts/LexendMega-Bold.ttf
          weight: 700
